name       : qt5-tools
version    : 5.6.2
release    : 1
source     :
        - http://download.qt.io/official_releases/qt/5.6/5.6.2/submodules/qttools-opensource-src-5.6.2.tar.xz : db2bb4318786257a47172c377d9c456d5d5ec760d5d69240a4693dc87989e1b7
license    :
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
    - GFDL-1.3
component  : desktop.qt
summary    : Qt5 QtTools Module
description: |
    Qt is a set of libraries for developing applications.  This package contains base tools, like string, xml, and network handling.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos :
        /usr/lib64/qt5/examples
setup      : |
    %qmake QMAKE_CFLAGS_ISYSTEM=-I CONFIG+=release qttools.pro
build      : |
    %make
install    : |
    %make INSTALL_ROOT="$installdir" install
    install -Dm00644 src/assistant/assistant/images/assistant.png $installdir/usr/share/icons/hicolor/32x32/apps/assistant.png
    install -Dm00644 src/assistant/assistant/images/assistant-128.png $installdir/usr/share/icons/hicolor/128x128/apps/assistant.png
    install -Dm00644 src/linguist/linguist/images/icons/linguist-32-32.png $installdir/usr/share/icons/hicolor/128x128/apps/linguist.png
    install -Dm00644 src/linguist/linguist/images/icons/linguist-128-32.png $installdir/usr/share/icons/hicolor/128x128/apps/linguist.png
    install -Dm00644 src/designer/src/designer/images/designer.png $installdir/usr/share/icons/hicolor/128x128/apps/designer.png
    install -Dm00644 src/qdbus/qdbusviewer/images/qdbusviewer.png $installdir/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png
    install -Dm00644 src/qdbus/qdbusviewer/images/qdbusviewer-128.png $installdir/usr/share/icons/hicolor/128x128/apps/qdbusviewer.png
    install -Dm00644 $pkgfiles/designer.desktop $installdir/usr/share/applications/designer.desktop
    install -Dm00644 $pkgfiles/linguist.desktop $installdir/usr/share/applications/linguist.desktop
    install -Dm00644 $pkgfiles/assistant.desktop $installdir/usr/share/applications/assistant.desktop
    install -Dm00644 $pkgfiles/qdbusviewer.desktop $installdir/usr/share/applications/qdbusviewer.desktop
