name       : qt5-tools
version    : 5.11.1
release    : 11
source     :
    - https://mirrors.ocf.berkeley.edu/qt/official_releases/qt/5.11/5.11.1/submodules/qttools-everywhere-src-5.11.1.tar.xz : b7fb186f92aedb922c4e7f57ff276bbf90caf0087a2a980f704bad9ac44514fe
license    :
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
    - GFDL-1.3
component  : desktop.qt
summary    : Qt5 QtTools Module
description: |
    Qt is a set of libraries for developing applications.  This package contains base tools, like string, xml, and network handling.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos : /usr/lib64/qt5/examples
    - devel :
        - /usr/bin
        - /usr/share/applications
        - /usr/share/icons
    - main :
        - /usr/bin/qdbus
        - /usr/bin/qtpaths
setup      : |
    %qmake CONFIG+=release qttools.pro
build      : |
    %make
install    : |
    %make INSTALL_ROOT="$installdir" install
    install -Dm00644 src/assistant/assistant/images/assistant.png $installdir/usr/share/icons/hicolor/32x32/apps/assistant.png
    install -Dm00644 src/assistant/assistant/images/assistant-128.png $installdir/usr/share/icons/hicolor/128x128/apps/assistant.png
    install -Dm00644 src/linguist/linguist/images/icons/linguist-32-32.png $installdir/usr/share/icons/hicolor/128x128/apps/linguist.png
    install -Dm00644 src/linguist/linguist/images/icons/linguist-128-32.png $installdir/usr/share/icons/hicolor/128x128/apps/linguist.png
    install -Dm00644 src/designer/src/designer/images/designer.png $installdir/usr/share/icons/hicolor/128x128/apps/designer.png
    install -Dm00644 src/qdbus/qdbusviewer/images/qdbusviewer.png $installdir/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png
    install -Dm00644 src/qdbus/qdbusviewer/images/qdbusviewer-128.png $installdir/usr/share/icons/hicolor/128x128/apps/qdbusviewer.png
    install -Dm00644 $pkgfiles/designer.desktop $installdir/usr/share/applications/designer.desktop
    install -Dm00644 $pkgfiles/linguist.desktop $installdir/usr/share/applications/linguist.desktop
    install -Dm00644 $pkgfiles/assistant.desktop $installdir/usr/share/applications/assistant.desktop
    install -Dm00644 $pkgfiles/qdbusviewer.desktop $installdir/usr/share/applications/qdbusviewer.desktop
